In [48]:
import numpy as np

In [49]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array([20, 27, 9, 12, 31, 17, 4, 50, 39, 35])

In [50]:
print(arr * 4)

[ 80 108  36  48 124  68  16 200 156 140]


In [51]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

24.4
23.5
13.828955130450023


In [52]:
print(np.argmin(arr))
print(np.argmax(arr))

6
7


In [53]:
print(arr.item(6))
print(arr.item(7))

4
50


In [54]:
print(np.min(arr))
print(np.max(arr))
#yes, the values match

4
50


In [55]:
new = arr > 20
new2 = arr[new]
print(new2)

[27 31 50 39 35]


In [56]:
list1 = [[5, 12, 17, 9],
          [8, 21, 14, 3],
          [6, 13, 19, 11]]
matrix = np.array(list1)
print(matrix)

[[ 5 12 17  9]
 [ 8 21 14  3]
 [ 6 13 19 11]]


In [57]:
print(matrix.shape)
#3 rows and 4 columns

(3, 4)


In [58]:
print(matrix[:, 2])
print(matrix[1, :])

[17 14 19]
[ 8 21 14  3]


In [59]:
print(matrix*2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [60]:
for i in range(matrix.shape[1]):
    column = matrix[:, i]
    print(np.mean(column))

6.333333333333333
15.333333333333334
16.666666666666668
7.666666666666667


In [61]:
print(np.mean(matrix))

11.5


In [62]:
for row in matrix:
    print(np.max(row))

for i in range(matrix.shape[1]):
    column = matrix[:, i]
    print(np.max(column))

17
21
19
8
21
19
11


In [63]:
new_matrix = matrix.flatten()
print(new_matrix)
#returned a 1d array with the same elements of the original, but in a single sequence

[ 5 12 17  9  8 21 14  3  6 13 19 11]


In [64]:
print(np.argmin(new_matrix))
print(np.argmax(new_matrix))

7
5


In [65]:
max_index = 5
min_index = 7
matrix_shape = matrix.shape
print(np.unravel_index(max_index, matrix_shape))
print(np.unravel_index(min_index, matrix_shape))

(np.int64(1), np.int64(1))
(np.int64(1), np.int64(3))


In [66]:
bool_values = matrix > 15
new_matrix = matrix[bool_values]
print(new_matrix)

[17 21 19]


In [67]:
np.sort(matrix)

array([[ 5,  9, 12, 17],
       [ 3,  8, 14, 21],
       [ 6, 11, 13, 19]])

In [68]:
arr = np.array([
    [2, 3, 5],
    [14, 16, 8],
    [11, 13, 17],
    [7, 10, 13]
])

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
        else:
            return True

def prime_rows(array):
    prime_rows = []
    for row in arr:
        if any(is_prime(x) for x in row):
            prime_rows.append(row)
    return np.array(prime_rows)

prime_star_rows = prime_rows(arr)
print(prime_star_rows)

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [69]:
def eightby():
    return np.zeros((8,8), dtype=int)
eightby()

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [70]:
arr = eightby()

for i in range(0, 8, 2):
    arr[i, ::2] = 1

print(arr)

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [71]:
def checkerboard():
    arr = eightby()
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr

checkerboard()

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [72]:
def reverse_checkerboard():
    arr = eightby()
    arr[::2, ::2] = 1
    arr[1::2, 1::2] = 1
    return arr

reverse_checkerboard()

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [75]:
def expansion():
    start_string = input("Type a word or phrase")
    input_spaces = int(input("How many spaces between letters?"))
    space_separator = " " * input_spaces
    return space_separator.join(start_string)

expansion()

Type a word or phrase expanding universe
How many spaces between letters? 3


'e   x   p   a   n   d   i   n   g       u   n   i   v   e   r   s   e'

In [94]:
def secondBrightest(array):
    guidestars = np.array([])
    for row in array:
        sorted_row = np.sort(row)[::1]
        guidestars = np.append(guidestars, sorted_row.item(1))
    return guidestars